export const countryData = [
  {value: 'SA', label: "Santorini", disabled: false},
  {value: 'DM', label: "DOMINICAN", disabled: false},
  { value: "AX", label: "AALAND ISLANDS", disabled: true },
  { value: "AF", label: "AFGHANISTAN", disabled: true },
  { value: "AL", label: "ALBANIA", disabled: true },
  { value: "DZ", disabled: true, label: "ALGERIA" },
  { value: "AS", disabled: true, label: "AMERICAN SAMOA" },
  { value: "AD", disabled: true, label: "ANDORRA" },
  { value: "AO", disabled: true, label: "ANGOLA" },
  { value: "AI", disabled: true, label: "ANGUILLA" },
  { value: "AQ", disabled: true, label: "ANTARCTICA" },
  { value: "AG", disabled: true, label: "ANTIGUA AND BARBUDA" },
  { value: "AR", disabled: true, label: "ARGENTINA" },
  { value: "AM", disabled: true, label: "ARMENIA" },
  { value: "AW", disabled: true, label: "ARUBA" },
  { value: "AU", disabled: true, label: "AUSTRALIA" },
  { value: "AT", disabled: true, label: "AUSTRIA" },
  { value: "AZ", disabled: true, label: "AZERBAIJAN" },
  { value: "BS", disabled: true, label: "BAHAMAS" },
  { value: "BH", disabled: true, label: "BAHRAIN" },
  { value: "BD", disabled: true, label: "BANGLADESH" },
  { value: "BB", disabled: true, label: "BARBADOS" },
  { value: "BY", disabled: true, label: "BELARUS" },
  { value: "BE", disabled: true, label: "BELGIUM" },
  { value: "BZ", disabled: true, label: "BELIZE" },
  { value: "BJ", disabled: true, label: "BENIN" },
  { value: "BM", disabled: true, label: "BERMUDA" },
  { value: "BT", disabled: true, label: "BHUTAN" },
  { value: "BO", disabled: true, label: "BOLIVIA" },
  { value: "BA", disabled: true, label: "BOSNIA AND HERZEGOWINA" },
  { value: "BW", disabled: true, label: "BOTSWANA" },
  { value: "BV", disabled: true, label: "BOUVET ISLAND" },
  { value: "BR", disabled: true, label: "BRAZIL" },
  { value: "IO", disabled: true, label: "BRITISH INDIAN OCEAN TERRITORY" },
  { value: "BN", disabled: true, label: "BRUNEI DARUSSALAM" },
  { value: "BG", disabled: true, label: "BULGARIA" },
  { value: "BF", disabled: true, label: "BURKINA FASO" },
  { value: "BI", disabled: true, label: "BURUNDI" },
  { value: "KH", disabled: true, label: "CAMBODIA" },
  { value: "CM", disabled: true, label: "CAMEROON" },
  { value: "CA", disabled: true, label: "CANADA" },
  { value: "CV", disabled: true, label: "CAPE VERDE" },
  { value: "KY", disabled: true, label: "CAYMAN ISLANDS" },
  { value: "CF", disabled: true, label: "CENTRAL AFRICAN REPUBLIC" },
  { value: "TD", disabled: true, label: "CHAD" },
  { value: "CL", disabled: true, label: "CHILE" },
  { value: "CN", disabled: true, label: "CHINA" },
  { value: "CX", disabled: true, label: "CHRISTMAS ISLAND" },
  { value: "CO", disabled: true, label: "COLOMBIA" },
  { value: "KM", disabled: true, label: "COMOROS" },
  { value: "CK", disabled: true, label: "COOK ISLANDS" },
  { value: "CR", disabled: true, label: "COSTA RICA" },
  { value: "CI", disabled: true, label: "COTE D'IVOIRE" },
  { value: "CU", disabled: true, label: "CUBA" },
  { value: "CY", disabled: true, label: "CYPRUS" },
  { value: "CZ", disabled: true, label: "CZECH REPUBLIC" },
  { value: "DK", disabled: true, label: "DENMARK" },
  { value: "DJ", disabled: true, label: "DJIBOUTI" },
  { value: "DM", disabled: true, label: "DOMINICA" },
  { value: "DO", disabled: true, label: "DOMINICAN REPUBLIC" },
  { value: "EC", disabled: true, label: "ECUADOR" },
  { value: "EG", disabled: true, label: "EGYPT" },
  { value: "SV", disabled: true, label: "EL SALVADOR" },
  { value: "GQ", disabled: true, label: "EQUATORIAL GUINEA" },
  { value: "ER", disabled: true, label: "ERITREA" },
  { value: "EE", disabled: true, label: "ESTONIA" },
  { value: "ET", disabled: true, label: "ETHIOPIA" },
  { value: "FO", disabled: true, label: "FAROE ISLANDS" },
  { value: "FJ", disabled: true, label: "FIJI" },
  { value: "FI", disabled: true, label: "FINLAND" },
  { value: "FR", disabled: true, label: "FRANCE" },
  { value: "GF", disabled: true, label: "FRENCH GUIANA" },
  { value: "PF", disabled: true, label: "FRENCH POLYNESIA" },
  { value: "TF", disabled: true, label: "FRENCH SOUTHERN TERRITORIES" },
  { value: "GA", disabled: true, label: "GABON" },
  { value: "GM", disabled: true, label: "GAMBIA" },
  { value: "GE", disabled: true, label: "GEORGIA" },
  { value: "DE", disabled: true, label: "GERMANY" },
  { value: "GH", disabled: true, label: "GHANA" },
  { value: "GI", disabled: true, label: "GIBRALTAR" },
  { value: "GR", disabled: true, label: "GREECE" },
  { value: "GL", disabled: true, label: "GREENLAND" },
  { value: "GD", disabled: true, label: "GRENADA" },
  { value: "GP", disabled: true, label: "GUADELOUPE" },
  { value: "GU", disabled: true, label: "GUAM" },
  { value: "GT", disabled: true, label: "GUATEMALA" },
  { value: "GN", disabled: true, label: "GUINEA" },
  { value: "GW", disabled: true, label: "GUINEA-BISSAU" },
  { value: "GY", disabled: true, label: "GUYANA" },
  { value: "HT", disabled: true, label: "HAITI" },
  { value: "HM", disabled: true, label: "HEARD AND MC DONALD ISLANDS" },
  { value: "HN", disabled: true, label: "HONDURAS" },
  { value: "HK", disabled: true, label: "HONG KONG" },
  { value: "HU", disabled: true, label: "HUNGARY" },
  { value: "IS", disabled: true, label: "ICELAND" },
  { value: "IN", disabled: true, label: "INDIA" },
  { value: "ID", disabled: true, label: "INDONESIA" },
  { value: "IQ", disabled: true, label: "IRAQ" },
  { value: "IE", disabled: true, label: "IRELAND" },
  { value: "IL", disabled: true, label: "ISRAEL" },
  { value: "IT", disabled: true, label: "ITALY" },
  { value: "JM", disabled: true, label: "JAMAICA" },
  { value: "JP", disabled: true, label: "JAPAN" },
  { value: "JO", disabled: true, label: "JORDAN" },
  { value: "KZ", disabled: true, label: "KAZAKHSTAN" },
  { value: "KE", disabled: true, label: "KENYA" },
  { value: "KI", disabled: true, label: "KIRIBATI" },
  { value: "KW", disabled: true, label: "KUWAIT" },
  { value: "KG", disabled: true, label: "KYRGYZSTAN" },
  { value: "LA", disabled: true, label: "LAO PEOPLE'S DEMOCRATIC REPUBLIC" },
  { value: "LV", disabled: true, label: "LATVIA" },
  { value: "LB", disabled: true, label: "LEBANON" },
  { value: "LS", disabled: true, label: "LESOTHO" },
  { value: "LR", disabled: true, label: "LIBERIA" },
  { value: "LY", disabled: true, label: "LIBYAN ARAB JAMAHIRIYA" },
  { value: "LI", disabled: true, label: "LIECHTENSTEIN" },
  { value: "LT", disabled: true, label: "LITHUANIA" },
  { value: "LU", disabled: true, label: "LUXEMBOURG" },
  { value: "MO", disabled: true, label: "MACAU" },
  { value: "MG", disabled: true, label: "MADAGASCAR" },
  { value: "MW", disabled: true, label: "MALAWI" },
  { value: "MY", disabled: true, label: "MALAYSIA" },
  { value: "MV", disabled: true, label: "MALDIVES" },
  { value: "ML", disabled: true, label: "MALI" },
  { value: "MT", disabled: true, label: "MALTA" },
  { value: "MH", disabled: true, label: "MARSHALL ISLANDS" },
  { value: "MQ", disabled: true, label: "MARTINIQUE" },
  { value: "MR", disabled: true, label: "MAURITANIA" },
  { value: "MU", disabled: true, label: "MAURITIUS" },
  { value: "YT", disabled: true, label: "MAYOTTE" },
  { value: "MX", disabled: true, label: "MEXICO" },
  { value: "MC", disabled: true, label: "MONACO" },
  { value: "MN", disabled: true, label: "MONGOLIA" },
  { value: "MS", disabled: true, label: "MONTSERRAT" },
  { value: "MA", disabled: true, label: "MOROCCO" },
  { value: "MZ", disabled: true, label: "MOZAMBIQUE" },
  { value: "MM", disabled: true, label: "MYANMAR" },
  { value: "NA", disabled: true, label: "NAMIBIA" },
  { value: "NR", disabled: true, label: "NAURU" },
  { value: "NP", disabled: true, label: "NEPAL" },
  { value: "NL", disabled: true, label: "NETHERLANDS" },
  { value: "AN", disabled: true, label: "NETHERLANDS ANTILLES" },
  { value: "NC", disabled: true, label: "NEW CALEDONIA" },
  { value: "NZ", disabled: true, label: "NEW ZEALAND" },
  { value: "NI", disabled: true, label: "NICARAGUA" },
  { value: "NE", disabled: true, label: "NIGER" },
  { value: "NG", disabled: true, label: "NIGERIA" },
  { value: "NU", disabled: true, label: "NIUE" },
  { value: "NF", disabled: true, label: "NORFOLK ISLAND" },
  { value: "MP", disabled: true, label: "NORTHERN MARIANA ISLANDS" },
  { value: "NO", disabled: true, label: "NORWAY" },
  { value: "OM", disabled: true, label: "OMAN" },
  { value: "PK", disabled: true, label: "PAKISTAN" },
  { value: "PW", disabled: true, label: "PALAU" },
  { value: "PA", disabled: true, label: "PANAMA" },
  { value: "PG", disabled: true, label: "PAPUA NEW GUINEA" },
  { value: "PY", disabled: true, label: "PARAGUAY" },
  { value: "PE", disabled: true, label: "PERU" },
  { value: "PH", disabled: true, label: "PHILIPPINES" },
  { value: "PN", disabled: true, label: "PITCAIRN" },
  { value: "PL", disabled: true, label: "POLAND" },
  { value: "PT", disabled: true, label: "PORTUGAL" },
  { value: "PR", disabled: true, label: "PUERTO RICO" },
  { value: "QA", disabled: true, label: "QATAR" },
  { value: "RE", disabled: true, label: "REUNION" },
  { value: "RO", disabled: true, label: "ROMANIA" },
  { value: "RU", disabled: true, label: "RUSSIAN FEDERATION" },
  { value: "RW", disabled: true, label: "RWANDA" },
  { value: "SH", disabled: true, label: "SAINT HELENA" },
  { value: "KN", disabled: true, label: "SAINT KITTS AND NEVIS" },
  { value: "LC", disabled: true, label: "SAINT LUCIA" },
  { value: "PM", disabled: true, label: "SAINT PIERRE AND MIQUELON" },
  { value: "VC", disabled: true, label: "SAINT VINCENT AND THE GRENADINES" },
  { value: "WS", disabled: true, label: "SAMOA" },
  { value: "SM", disabled: true, label: "SAN MARINO" },
  { value: "ST", disabled: true, label: "SAO TOME AND PRINCIPE" },
  { value: "SA", disabled: true, label: "SAUDI ARABIA" },
  { value: "SN", disabled: true, label: "SENEGAL" },
  { value: "CS", disabled: true, label: "SERBIA AND MONTENEGRO" },
  { value: "SC", disabled: true, label: "SEYCHELLES" },
  { value: "SL", disabled: true, label: "SIERRA LEONE" },
  { value: "SG", disabled: true, label: "SINGAPORE" },
  { value: "SK", disabled: true, label: "SLOVAKIA" },
  { value: "SI", disabled: true, label: "SLOVENIA" },
  { value: "SB", disabled: true, label: "SOLOMON ISLANDS" },
  { value: "SO", disabled: true, label: "SOMALIA" },
  { value: "ZA", disabled: true, label: "SOUTH AFRICA" },
  {
    value: "GS",
    disabled: true,
    label: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
  },
  { value: "ES", disabled: true, label: "SPAIN" },
  { value: "LK", disabled: true, label: "SRI LANKA" },
  { value: "SD", disabled: true, label: "SUDAN" },
  { value: "SR", disabled: true, label: "SURINAME" },
  { value: "SJ", disabled: true, label: "SVALBARD AND JAN MAYEN ISLANDS" },
  { value: "SZ", disabled: true, label: "SWAZILAND" },
  { value: "SE", disabled: true, label: "SWEDEN" },
  { value: "CH", disabled: true, label: "SWITZERLAND" },
  { value: "SY", disabled: true, label: "SYRIAN ARAB REPUBLIC" },
  { value: "TW", disabled: true, label: "TAIWAN" },
  { value: "TJ", disabled: true, label: "TAJIKISTAN" },
  { value: "TH", disabled: true, label: "THAILAND" },
  { value: "TL", disabled: true, label: "TIMOR-LESTE" },
  { value: "TG", disabled: true, label: "TOGO" },
  { value: "TK", disabled: true, label: "TOKELAU" },
  { value: "TO", disabled: true, label: "TONGA" },
  { value: "TT", disabled: true, label: "TRINIDAD AND TOBAGO" },
  { value: "TN", disabled: true, label: "TUNISIA" },
  { value: "TR", disabled: true, label: "TURKEY" },
  { value: "TM", disabled: true, label: "TURKMENISTAN" },
  { value: "TC", disabled: true, label: "TURKS AND CAICOS ISLANDS" },
  { value: "TV", disabled: true, label: "TUVALU" },
  { value: "UG", disabled: true, label: "UGANDA" },
  { value: "UA", disabled: true, label: "UKRAINE" },
  { value: "AE", disabled: true, label: "UNITED ARAB EMIRATES" },
  { value: "GB", disabled: true, label: "UNITED KINGDOM" },
  { value: "US", disabled: true, label: "UNITED STATES" },
  {
    value: "UM",
    disabled: true,
    label: "UNITED STATES MINOR OUTLYING ISLANDS",
  },
  { value: "UY", disabled: true, label: "URUGUAY" },
  { value: "UZ", disabled: true, label: "UZBEKISTAN" },
  { value: "VU", disabled: true, label: "VANUATU" },
  { value: "VE", disabled: true, label: "VENEZUELA" },
  { value: "VN", disabled: true, label: "VIET NAM" },
  { value: "WF", disabled: true, label: "WALLIS AND FUTUNA ISLANDS" },
  { value: "EH", disabled: true, label: "WESTERN SAHARA" },
  { value: "YE", disabled: true, label: "YEMEN" },
  { value: "ZM", disabled: true, label: "ZAMBIA" },
  { value: "ZW", disabled: true, label: "ZIMBvalabel" },
];